---
- hosts: localhost
  tasks:
    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: trainee5
        location: East US
      register: rg

    - name: Create virtual network

                        azure_rm_virtualnetwork:

                                name: <traineeid>vnet

                                        resource_group: <traineeid>

                                                address_prefixes_cidr: 10.0.0.0/16

                                                      register: vnet



                                                          - name: Create subnet

                                                                azure_rm_subnet:

                                                                        name: <traineeid>subnet

                                                                                resource_group: <traineeid>

                                                                                        virtual_network_name: <traineeid>vnet

                                                                                                address_prefixes: "10.0.0.0/24"



                                                                                                    - name: Create Public IP address

                                                                                                          azure_rm_publicipaddress:

                                                                                                                  name: <traineeid>publicip

                                                                                                                          resource_group: <traineeid>

                                                                                                                                  allocation_method: Dynamic



                                                                                                                                      - name: Create network unterface

                                                                                                                                            azure_rm_networkinterface:

                                                                                                                                                    name: <traineeid>nic

                                                                                                                                                            resource_group: <traineeid>

                                                                                                                                                                    location: East US

                                                                                                                                                                            virtual_network_name: <traineeid>vnet

                                                                                                                                                                                    subnet_name: <traineeid>subnet

                                                                                                                                                                                            public_ip_name: <traineeid>publicip



                                                                                                                                                                                                - name: Create a network security group

                                                                                                                                                                                                      azure_rm_securitygroup:

                                                                                                                                                                                                              name: <traineeid>nsg

                                                                                                                                                                                                                      resource_group: <traineeid>

                                                                                                                                                                                                                              rules:

                                                                                                                                                                                                                                        - name: SSH

                                                                                                                                                                                                                                                    access: Allow

                                                                                                                                                                                                                                                                direction: Inbound

                                                                                                                                                                                                                                                                            priority: 100

                                                                                                                                                                                                                                                                                        protocol: Tcp

                                                                                                                                                                                                                                                                                                    source_port_range: "*"

                                                                                                                                                                                                                                                                                                                source_address_prefix: "*"

                                                                                                                                                                                                                                                                                                                            destination_port_range: 22

                                                                                                                                                                                                                                                                                                                                        destination_address_prefix: "*"



                                                                                                                                                                                                                                                                                                                                            - name: Create virtual machine

                                                                                                                                                                                                                                                                                                                                                  azure_rm_virtualmachine:

                                                                                                                                                                                                                                                                                                                                                          name: <traineeid>vm

                                                                                                                                                                                                                                                                                                                                                                  resource_group: <traineeid>

                                                                                                                                                                                                                                                                                                                                                                          location: East US

                                                                                                                                                                                                                                                                                                                                                                                  vm_size: Standard_D2s_v3

                                                                                                                                                                                                                                                                                                                                                                                          admin_username: <traineeid>

                                                                                                                                                                                                                                                                                                                                                                                                  admin_password: TrainerP@ssw0rd

                                                                                                                                                                                                                                                                                                                                                                                                          image:

                                                                                                                                                                                                                                                                                                                                                                                                                    offer: UbuntuServer

                                                                                                                                                                                                                                                                                                                                                                                                                              publisher: Canonical

                                                                                                                                                                                                                                                                                                                                                                                                                                        sku: 18.04-LTS

                                                                                                                                                                                                                                                                                                                                                                                                                                                  version: 18.04.201804262

                                                                                                                                                                                                                                                                                                                                                                                                                                                          network_interfaces: <traineeid>nic


